// Chapters three to six, references and appendices.

const CH3 = [
  { t: 'h2', n: '3.1', x: 'Introduction' },
  { t: 'p', x: 'This chapter describes the methods used to study the existing maternal emergency response workflow in Mukono District, to elicit and specify the requirements of the new system, and to design, implement, test and validate it. It covers the research design, the population and sampling strategy, the instruments used and their testing, the data collection and analysis methods, and the systems analysis, design, implementation and validation methods adopted under the Systems Development Life Cycle.' },

  { t: 'h2', n: '3.2', x: 'Research Design' },
  { t: 'p', x: 'The study adopted a descriptive and developmental research design combining qualitative and quantitative approaches. The descriptive component established how maternal emergencies are currently reported, triaged and dispatched in Mukono District and where time is lost in that pathway. The developmental component produced the software artefact itself and evaluated it against the workflow it was designed to replace.' },
  { t: 'p', x: 'An iterative and incremental Systems Development Life Cycle was used rather than a strictly sequential one. Because the essential risk in this system is behavioural rather than computational — whether a responder can act on a location under time pressure — the design had to be exposed to stakeholders early and repeatedly. Each iteration delivered a working portal that could be demonstrated, criticised and revised before the next was started.' },

  { t: 'h2', n: '3.3', x: 'Population and Sample Selection' },
  { t: 'h3', n: '3.3.1', x: 'Sampling Strategy' },
  { t: 'p', x: 'The study population comprised the stakeholders in the maternal emergency referral pathway in Mukono District: expectant mothers attending antenatal care, midwives and obstetricians at Mukono General Hospital and surrounding health centres, ambulance drivers, Village Health Team members, and district health administrators.' },
  { t: 'p', x: 'Purposive sampling was used for clinical staff, drivers and administrators, because the information required — how a dispatch is actually decided and executed — is held only by those who perform the task. Convenience sampling was used for expectant mothers attending antenatal clinics on the days of data collection, since the relevant characteristic is shared across the group.' },
  { t: 'h3', n: '3.3.2', x: 'Sample Size Determination' },
  { t: 'p', x: 'A total sample of 60 respondents was drawn, distributed as shown in Table 3.1. The size was determined by the point of thematic saturation for the qualitative instruments rather than by statistical power, since the purpose of data collection was requirements elicitation rather than hypothesis testing.' },
  {
    t: 'tbl', n: '3.1', cap: 'Distribution of the Study Sample',
    head: ['Respondent category', 'Sampling method', 'Number', 'Instrument used'],
    widths: [3100, 2400, 1200, 2660],
    rows: [
      ['Expectant mothers', 'Convenience', '25', 'Questionnaire'],
      ['Midwives and obstetricians', 'Purposive', '12', 'Interview'],
      ['Village Health Team members', 'Purposive', '12', 'Questionnaire and interview'],
      ['Ambulance drivers', 'Purposive', '6', 'Interview and observation'],
      ['District health administrators', 'Purposive', '5', 'Interview and document review'],
      ['Total', '', '60', ''],
    ],
  },

  { t: 'h2', n: '3.4', x: 'Research Instrument Design and Testing' },
  { t: 'h3', n: '3.4.1', x: 'Reliability Testing' },
  { t: 'p', x: 'The questionnaire was piloted with eight respondents drawn from outside the main sample. Items that produced inconsistent responses on repeat administration were reworded, and two items that duplicated each other were merged. Internal consistency across the scaled items was judged acceptable before the instrument was administered.' },
  { t: 'h3', n: '3.4.2', x: 'Validity Testing' },
  { t: 'p', x: 'Content validity was established by submitting the draft instruments to the research supervisor and to a senior midwife at Mukono General Hospital for review against the study objectives. Items that did not map to a specific objective were removed. Construct validity was supported by deriving the instrument sections directly from the constructs in the conceptual framework: spatial invisibility, the second delay and referral coordination.' },

  { t: 'h2', n: '3.5', x: 'Data Collection and Analysis Methods' },
  { t: 'h3', n: '3.5.1', x: 'Interview Method' },
  { t: 'p', x: 'Semi-structured interviews were conducted with clinical staff, ambulance drivers and district administrators. This method was chosen because the existing dispatch procedure is undocumented and exists mainly as practitioner knowledge; an open format allowed respondents to describe the workflow in their own terms and to recount specific incidents in which locating a patient failed.' },
  { t: 'h3', n: '3.5.2', x: 'Questionnaire Method' },
  { t: 'p', x: 'Structured questionnaires were administered to expectant mothers and Village Health Team members. The instrument captured device ownership, network availability at the respondent’s home, the means currently used to summon help, and the time typically taken for assistance to arrive. This method was appropriate for the larger and more homogeneous group, where comparable responses across many respondents were more valuable than depth.' },
  { t: 'h3', n: '3.5.3', x: 'Document Review Method' },
  { t: 'p', x: 'Facility referral registers, ambulance logbooks and antenatal cards were reviewed to corroborate the reported timings and to establish the data items already recorded in the manual system. This review directly informed the attribute set of the database entities described in Chapter Five.' },
  { t: 'h3', n: '3.5.4', x: 'Observation Method' },
  { t: 'p', x: 'The dispatch process was observed at Mukono General Hospital in order to record what actually happens between a call being received and an ambulance departing, as distinct from what respondents reported happens. Observation established the handover points at which information is lost.' },
  { t: 'h3', n: '3.5.5', x: 'Data Analysis Methods' },
  { t: 'p', x: 'Quantitative responses were summarised using descriptive statistics — frequencies, percentages and means — to characterise device ownership, connectivity and reported response times. Qualitative interview and observation data were analysed thematically: transcripts were coded, codes were grouped into themes, and the themes were mapped onto the requirement categories presented in Chapter Four. Analysis was iterative, with findings from early interviews shaping the questions asked in later ones.' },

  { t: 'h2', n: '3.6', x: 'Systems Study and Analysis Methods' },
  { t: 'h3', n: '3.6.1', x: 'Systems Study Methods' },
  { t: 'p', x: 'The current system was studied through observation of the live dispatch workflow, interviews with its operators and review of the records it produces. The workflow was reconstructed as a sequence of handovers from the mother to a relative or Village Health Team member, from there by telephone to a facility, and from the facility to a driver, in order to identify where location information degrades.' },
  { t: 'h3', n: '3.6.2', x: 'Systems Analysis Methods' },
  { t: 'p', x: 'SWOT analysis was used to evaluate the current system, since it accommodates both what the existing arrangement does well — notably the trust and community reach of Village Health Teams — and what it does poorly, without discarding the former. Process decomposition was then applied to break the emergency pathway into the discrete processes later modelled as Data Flow Diagrams.' },

  { t: 'h2', n: '3.7', x: 'System Requirements and Specification' },
  { t: 'p', x: 'Requirements were specified in four categories. User requirements express what each stakeholder must be able to accomplish, stated in the stakeholder’s own terms. Functional requirements express what the system must do in response. Non-functional requirements express the qualities the system must exhibit while doing it, chiefly availability under intermittent connectivity and speed of alert propagation. System requirements express the hardware and software environment needed to run it. The specifications produced are presented in full in Chapter Four.' },

  { t: 'h2', n: '3.8', x: 'Systems Design and Modelling Methods' },
  { t: 'h3', n: '3.8.1', x: 'Design and Modelling Using Data Flow Diagrams' },
  { t: 'p', x: 'Data Flow Diagrams were used to model the movement of information through the system. A context diagram fixed the system boundary and identified the external entities and services with which the system exchanges data. This was decomposed into a level 0 diagram showing the principal processes and data stores, and further into a level 1 diagram decomposing the emergency dispatch process, which carries the study’s central concern.' },
  { t: 'h3', n: '3.8.2', x: 'Design and Modelling Using Entity-Relationship Diagrams' },
  { t: 'p', x: 'An Entity-Relationship Diagram was used to model the persistent data. Entities and their attributes were derived from the document review, and cardinality was expressed in crow’s-foot notation. The resulting model was translated into the relational schema described in Chapter Five.' },
  { t: 'h3', n: '3.8.3', x: 'Design and Modelling Using the Unified Modeling Language' },
  { t: 'p', x: 'Three UML views were used. A use case diagram expressed the functionality available to each of the five actors. A state machine diagram expressed the lifecycle of an emergency case and the permitted transitions between its states, which govern what each portal may do to a case at any moment. A sequence diagram expressed the ordered exchange of messages during a dispatch, from the mother pressing the alert to the receiving clinician being briefed.' },

  { t: 'h2', n: '3.9', x: 'System Implementation, Testing and Validation Methods' },
  { t: 'h3', n: '3.9.1', x: 'System Implementation Methods' },
  { t: 'p', x: 'The system was implemented as a Progressive Web Application rather than as a native mobile application. This decision follows directly from the constraints identified in the literature: a web application requires no installation from an application store, runs on the low-cost Android devices prevalent in the district, and can be updated centrally without asking users on limited data plans to download new versions. It was built with React and TypeScript, using Leaflet with OpenStreetMap tiles for mapping and Supabase PostgreSQL for shared persistence, and was developed incrementally, one portal at a time.' },
  { t: 'h3', n: '3.9.2', x: 'System Testing Methods' },
  { t: 'p', x: 'Testing was conducted at four levels. Unit-level checking used the TypeScript compiler and a static analysis tool to verify type correctness and code quality across all modules. Integration testing verified that a change written by one portal reaches the others through the synchronisation layer. System testing exercised each portal in a browser, checking rendering, data loading and error output. Acceptance testing took the form of simulated emergency scenarios executed end to end, described in Section 5.6.' },
  { t: 'h3', n: '3.9.3', x: 'System Validation Methods' },
  { t: 'p', x: 'Validation asked whether the system solves the problem stated in Chapter One, not merely whether it runs. The primary validation criterion was therefore whether an emergency raised on one device becomes visible, with an accurate position and an assigned responder, on a physically separate device belonging to a different actor, without any shared local state between them. This directly tests the elimination of spatial invisibility. Secondary criteria covered automatic facility and vehicle assignment, correct progression of the dispatch state machine, and continued operation when connectivity is lost.' },

  { t: 'h2', n: '3.10', x: 'Chapter Summary' },
  { t: 'p', x: 'This chapter has described the descriptive and developmental research design adopted, the purposive and convenience sampling of sixty respondents across five stakeholder categories, and the interview, questionnaire, document review and observation methods used to collect data. It has set out the SWOT and process decomposition methods used to analyse the current system, the Data Flow, Entity-Relationship and UML methods used to model the new one, and the implementation, testing and validation approach applied to the delivered software. The findings of the systems study are presented in Chapter Four.' },
];

const CH4 = [
  { t: 'h2', n: '4.1', x: 'Introduction' },
  { t: 'p', x: 'This chapter presents the findings of the systems study. It describes the current maternal emergency response system in Mukono District and evaluates it using SWOT analysis, then sets out the user, functional, non-functional and system requirements established for the new system, and presents the use case model derived from them.' },

  { t: 'h2', n: '4.2', x: 'Description of the Current System' },
  { t: 'p', x: 'The current system is a manual, telephone-mediated referral process. When an expectant mother experiences a complication, she or a relative contacts a Village Health Team member or a health facility by voice call. The caller describes the location verbally, typically by reference to landmarks, a trading centre, a church or a named neighbour, because no formal addressing system covers the rural sub-counties. The receiving facility decides whether to dispatch an ambulance, telephones a driver, and relays the same verbal description onward.' },
  { t: 'p', x: 'The mother’s clinical history exists on a paper antenatal card held by the mother herself. Consequently the receiving clinician learns the patient’s blood type, gravidity, parity and known complications only on arrival, and the driver carries no medical brief at all. Facility capability — whether beds are free, whether a blood bank is stocked, whether surgical capacity is available — is established by telephoning each facility in turn, which is why mothers are sometimes moved between facilities that cannot treat them.' },
  { t: 'p', x: 'Observation established that the greatest single loss of time occurs after dispatch and before arrival at the patient, while the driver searches for a home that has been described but not located. Respondents reported search times of up to an hour in the poorly mapped areas of Nama and considerably longer where lake transport to Koome is involved.' },

  { t: 'h3', n: '4.2.1', x: 'Strengths of the Current System' },
  { t: 'b', x: 'Village Health Teams hold established trust within their communities and are usually the first point of contact, giving the pathway genuine community reach.' },
  { t: 'b', x: 'The process requires no specialised equipment beyond a basic mobile handset and functions on any network.' },
  { t: 'b', x: 'Operators are experienced and can improvise, using local knowledge to interpret vague directions in areas they know well.' },
  { t: 'b', x: 'Paper antenatal cards remain readable without power or connectivity and travel with the patient.' },

  { t: 'h3', n: '4.2.2', x: 'Weaknesses of the Current System' },
  { t: 'b', x: 'Location is transmitted as description rather than as coordinates, so accuracy degrades at every handover and cannot be verified.' },
  { t: 'b', x: 'No responder can see where the ambulance is, so no arrival time can be given to the waiting family or the receiving facility.' },
  { t: 'b', x: 'Facility capability is not visible, producing referral loops between facilities that lack the resources required.' },
  { t: 'b', x: 'Clinical history arrives with the patient rather than ahead of her, so the receiving team cannot prepare.' },
  { t: 'b', x: 'No record of the emergency is retained beyond a logbook entry, so the district cannot identify where delays concentrate.' },
  { t: 'b', x: 'The pathway depends on voice calls and therefore fails where network coverage is weak, which is precisely where transit times are longest.' },

  { t: 'h3', n: '4.2.3', x: 'Comparative Analysis of the Strengths and Weaknesses' },
  { t: 'p', x: 'The comparison in Table 4.1 shows that the strengths of the current system are social and organisational while its weaknesses are informational. The community trust, improvisational skill and equipment independence that make the current pathway workable are not features a software system provides, and would be lost if the new system attempted to replace rather than extend them. Conversely, every weakness identified concerns the capture, transmission or retention of information, which is exactly what a software system does provide.' },
  { t: 'p', x: 'This asymmetry determined the design stance adopted: the new system augments the existing pathway rather than replacing it. Village Health Teams remain the field entry point and gain a device-based means of registering mothers and raising alerts; clinicians retain their triage authority and gain advance visibility of an inbound patient; drivers retain their route knowledge and gain a coordinate to navigate to.' },
  {
    t: 'tbl', n: '4.1', cap: 'Comparative Analysis of the Current System',
    head: ['Dimension', 'Current system', 'Consequence for the mother'],
    widths: [2300, 3560, 3500],
    rows: [
      ['Locating the patient', 'Verbal landmarks relayed by telephone', 'Search time of up to an hour before transport begins'],
      ['Tracking the ambulance', 'None; position unknown once dispatched', 'No arrival time can be given to the family or facility'],
      ['Facility capability', 'Established by telephoning each facility', 'Referral loops between facilities that cannot treat her'],
      ['Clinical history', 'Paper card carried by the mother', 'Receiving team cannot prepare before arrival'],
      ['Record retention', 'Logbook entry only', 'District cannot identify where delays concentrate'],
      ['Behaviour without network', 'Pathway stops entirely', 'Worst coverage coincides with longest transit'],
    ],
  },

  { t: 'h2', n: '4.3', x: 'Requirements of the New System' },
  { t: 'h3', n: '4.3.1', x: 'User Requirements' },
  { t: 'b', x: 'An expectant mother requires a means of summoning help in a single action, without typing an address, and of knowing that help has been assigned and is approaching.' },
  { t: 'b', x: 'A Village Health Team member requires a means of registering the mothers under their care, recording the findings of a home visit, and raising an alert on a mother’s behalf.' },
  { t: 'b', x: 'A clinician requires advance notice of an inbound patient together with her clinical history, and a means of requesting blood ahead of arrival.' },
  { t: 'b', x: 'An ambulance driver requires the patient’s coordinates, a route to them, the destination facility and a brief on the patient’s condition.' },
  { t: 'b', x: 'A district administrator requires a single view of active emergencies, fleet position and facility capacity, and a record from which to plan.' },

  { t: 'h3', n: '4.3.2', x: 'Functional Requirements' },
  {
    t: 'tbl', n: '4.2', cap: 'Functional Requirements of the New System',
    head: ['Ref', 'The system shall', 'Serves objective'],
    widths: [900, 6560, 1900],
    rows: [
      ['FR1', 'Register expectant mothers with their obstetric history, home coordinates and next of kin.', 'Objective ii'],
      ['FR2', 'Capture the mother’s current position from the device and attach it to an emergency alert.', 'Objective iii'],
      ['FR3', 'Raise an emergency alert from a single action on the mother’s device or on her behalf by a VHT.', 'Objective iii'],
      ['FR4', 'Resolve the nearest facility able to treat the case, taking bed availability and capability into account.', 'Objective iii'],
      ['FR5', 'Assign an available ambulance and driver to the case automatically and notify them.', 'Objective iii'],
      ['FR6', 'Notify the receiving clinician with the patient’s identity, position and clinical history.', 'Objective iii'],
      ['FR7', 'Display all active emergencies, facilities and vehicles on a live district map.', 'Objective iii'],
      ['FR8', 'Track the case through its dispatch states and record every transition with its actor and time.', 'Objective iv'],
      ['FR9', 'Allow the mother or the dispatcher to cancel an alert before pickup.', 'Objective iii'],
      ['FR10', 'Record antenatal vitals and home visit findings and flag readings outside safe ranges.', 'Objective ii'],
      ['FR11', 'Send SMS notification to the registered next of kin when an alert is raised.', 'Objective iii'],
      ['FR12', 'Replicate all changes between devices so that every actor sees the same case state.', 'Objective iii'],
      ['FR13', 'Queue changes made without connectivity and transmit them when the network returns.', 'Objective ii'],
      ['FR14', 'Produce district-level reports of emergencies, response times and facility utilisation.', 'Objective iv'],
    ],
  },

  { t: 'h3', n: '4.3.3', x: 'Non-Functional Requirements' },
  {
    t: 'tbl', n: '4.3', cap: 'Non-Functional Requirements of the New System',
    head: ['Ref', 'Quality', 'Requirement'],
    widths: [900, 2300, 6160],
    rows: [
      ['NFR1', 'Availability', 'The mother’s alert function shall remain usable when the device is offline, with the alert queued for transmission.'],
      ['NFR2', 'Timeliness', 'An alert raised on one device shall appear on the command console within seconds of being raised while connectivity exists.'],
      ['NFR3', 'Usability', 'The alert action shall be reachable within one interaction from the mother’s home screen and shall not require typed input.'],
      ['NFR4', 'Portability', 'The system shall run in a mobile browser on low-cost Android devices without installation from an application store.'],
      ['NFR5', 'Efficiency', 'Each portal shall be delivered as a separate bundle so that a mother downloads only her own interface.'],
      ['NFR6', 'Reliability', 'Loss of the realtime channel shall degrade the system to queued synchronisation rather than interrupting service.'],
      ['NFR7', 'Security', 'Access shall be scoped by role, and patient data shall be readable only by the actors involved in that patient’s care.'],
      ['NFR8', 'Maintainability', 'The source shall pass static type checking and lint analysis without errors or warnings.'],
    ],
  },

  { t: 'h3', n: '4.3.4', x: 'System Requirements' },
  {
    t: 'tbl', n: '4.4', cap: 'Hardware and Software Requirements',
    head: ['Component', 'Minimum requirement'],
    widths: [3200, 6160],
    rows: [
      ['Mother / VHT / driver device', 'Android smartphone, 2 GB RAM, GPS receiver, modern mobile browser'],
      ['Clinician and administrator workstation', 'Any desktop or laptop with a modern browser and a screen of 1280 px or wider'],
      ['Connectivity', 'Intermittent 3G or better; the system remains usable offline and synchronises on reconnection'],
      ['Server platform', 'Supabase managed PostgreSQL with realtime replication enabled'],
      ['Application hosting', 'Static hosting with HTTPS; no application server required'],
      ['Development environment', 'Node.js 18 or later, npm, and a modern browser with developer tools'],
    ],
  },

  { t: 'h3', n: '4.3.5', x: 'Use Case Model' },
  { t: 'p', x: 'The functional requirements were expressed as a use case model identifying the five actors and the cases available to each. The model shown in Figure 4.1 makes explicit which cases are shared — viewing the live map and receiving alerts are available to several actors — and which are exclusive, such as the approval of a dispatch, which only the district administrator may perform.' },
  { t: 'fig', n: '4.1', cap: 'Use Case Diagram of the Proposed System', img: 'fig07_use_case.png' },

  { t: 'h2', n: '4.4', x: 'Chapter Summary' },
  { t: 'p', x: 'This chapter described the current manual referral system in Mukono District and evaluated it, establishing that its strengths are social while its weaknesses are informational — an asymmetry that determined the decision to augment rather than replace the existing pathway. It then set out fourteen functional requirements, eight non-functional requirements and the hardware and software environment for the new system, and presented the use case model derived from them. The design and implementation that realise these requirements are presented in Chapter Five.' },
];

const CH5 = [
  { t: 'h2', n: '5.1', x: 'Introduction' },
  { t: 'p', x: 'This chapter presents the design of the system using Data Flow and Entity-Relationship diagrams, describes the database design, sets out how the system was implemented and on what platform, and reports the testing and validation carried out against the requirements established in Chapter Four.' },

  { t: 'h2', n: '5.2', x: 'System Design Using Data Flow Diagrams' },
  { t: 'h3', n: '5.2.1', x: 'Context Diagram' },
  { t: 'p', x: 'The context diagram in Figure 5.1 fixes the system boundary. It shows the system as a single process exchanging data with its five human actors and with three external services: the device geolocation provider that supplies coordinates, the OpenStreetMap tile service that supplies the basemap, and the Supabase cloud database that holds shared state. Every flow crossing this boundary is either a location, a clinical fact or a dispatch instruction.' },
  { t: 'fig', n: '5.1', cap: 'Context Diagram of the MamaTrack GPS System', img: 'fig03_context_diagram.png' },
  { t: 'h3', n: '5.2.2', x: 'Level 0 Diagram' },
  { t: 'p', x: 'The level 0 diagram in Figure 5.2 decomposes the single process into the five principal processes of the system — registration and profile management, emergency capture, dispatch coordination, monitoring and tracking, and reporting — and shows the data stores each reads from and writes to.' },
  { t: 'fig', n: '5.2', cap: 'Data Flow Diagram, Level 0', img: 'fig04_dfd_level0.png' },
  { t: 'h3', n: '5.2.3', x: 'Level 1 Diagram' },
  { t: 'p', x: 'The emergency dispatch process, which carries the central concern of the study, is decomposed further in Figure 5.3. It shows beacon capture, resolution of the nearest capable facility, ambulance and driver assignment, clinical notification and status tracking as distinct sub-processes, together with the stores each consults.' },
  { t: 'fig', n: '5.3', cap: 'Data Flow Diagram, Level 1 — Emergency Dispatch', img: 'fig05_dfd_level1.png' },

  { t: 'h2', n: '5.3', x: 'System Design Using Entity-Relationship Diagrams' },
  { t: 'h3', n: '5.3.1', x: 'Identified Entities and Their Attributes' },
  { t: 'p', x: 'Eleven entities were identified from the document review and requirements analysis. The users entity forms the identity spine of the model: mothers, doctors, drivers and Village Health Team members each extend it one-to-one with role-specific attributes rather than duplicating identity data. The emergencies entity is the central transaction record, referencing the mother, the facility, the vehicle, the driver and the receiving clinician, and carrying the coordinates and severity of the case.' },
  { t: 'h3', n: '5.3.2', x: 'Entity Diagram' },
  { t: 'fig', n: '5.4', cap: 'Entity-Relationship Diagram of the MamaTrack GPS Database', img: 'fig06_er_diagram.png' },
  { t: 'note', x: 'Note. Cardinality is shown in crow’s-foot notation. Referential integrity is enforced in the application layer rather than by database constraints, because replicated rows may arrive out of order — an emergency may reach a device before the mother record it references.' },

  { t: 'h2', n: '5.4', x: 'Database Design' },
  { t: 'h3', n: '5.4.1', x: 'Database Tables' },
  {
    t: 'tbl', n: '5.1', cap: 'Database Tables and Their Relationships',
    head: ['Table', 'Holds', 'Key relationships'],
    widths: [2000, 4160, 3200],
    rows: [
      ['users', 'Identity, role, contact details, active state', 'Parent of all role tables'],
      ['mothers', 'Obstetric history, home coordinates, next of kin', 'One-to-one with users'],
      ['doctors', 'Specialisation, licence number, duty state', 'One-to-one with users; many-to-one with hospitals'],
      ['drivers', 'Duty state, live vehicle position', 'One-to-one with users; many-to-one with vehicles'],
      ['hospitals', 'Location, bed count, CEmONC and blood bank capability', 'Referenced by emergencies and vehicles'],
      ['vehicles', 'Plate number, status, current coordinates', 'Many-to-one with hospitals'],
      ['emergencies', 'Case code, coordinates, severity, assignments, ETA', 'Central transaction table'],
      ['emergency_logs', 'Every status transition and the actor who caused it', 'Many-to-one with emergencies'],
      ['vitals', 'Blood pressure, glucose, foetal kick counts', 'Many-to-one with mothers'],
      ['vht_visits', 'Home visit findings and risk flags', 'Many-to-one with mothers and with the VHT user'],
      ['notifications', 'Per-user alerts and their read state', 'Many-to-one with users'],
    ],
  },
  { t: 'h3', n: '5.4.2', x: 'Data Descriptions' },
  { t: 'p', x: 'Table 5.2 gives the data description for the emergencies table, which is the central record of the system. The remaining table definitions follow the same pattern and are given in full in the schema listed in Appendix VI.' },
  {
    t: 'tbl', n: '5.2', cap: 'Data Description of the Emergencies Table',
    head: ['Attribute', 'Type', 'Description'],
    widths: [2100, 1700, 5560],
    rows: [
      ['id', 'Integer', 'Primary key uniquely identifying the emergency case'],
      ['code', 'Text', 'Human-readable case reference, for example EMG-2026-0031'],
      ['mother_id', 'Integer', 'Foreign key to the user account of the mother in distress'],
      ['latitude', 'Numeric', 'Latitude captured from the device at the moment the alert was raised'],
      ['longitude', 'Numeric', 'Longitude captured from the device at the moment the alert was raised'],
      ['status', 'Text', 'Current dispatch state: pending, dispatched, en-route, arrived, delivered, completed or cancelled'],
      ['severity', 'Text', 'Triage severity assigned to the case'],
      ['hospital_id', 'Integer', 'Foreign key to the facility resolved as the destination'],
      ['driver_id', 'Integer', 'Foreign key to the driver assigned to the case'],
      ['doctor_id', 'Integer', 'Foreign key to the clinician notified to receive the patient'],
      ['vehicle_id', 'Integer', 'Foreign key to the ambulance assigned to the case'],
      ['eta_minutes', 'Integer', 'Estimated time in minutes for the ambulance to reach the patient'],
      ['created_at', 'Timestamp', 'Moment the alert was raised, used to measure response time'],
    ],
  },

  { t: 'h2', n: '5.5', x: 'System Implementation' },
  { t: 'p', x: 'The system was implemented as a Progressive Web Application comprising five role-specific portals served from a single codebase over one shared data layer. It was built with React 18 and TypeScript 5.6, bundled with Vite 5.4, and routed with React Router 6. Mapping uses the Leaflet library with OpenStreetMap and CARTO raster tiles, rendered in a light or dark basemap according to the viewer’s theme. Shared persistence uses Supabase, a managed PostgreSQL service with realtime replication. The delivered source comprises approximately 18,000 lines across 25 TypeScript modules.' },
  { t: 'p', x: 'The architecture in Figure 5.5 shows how these parts relate. The decisive design choice is that the browser writes to a local store first and replicates to PostgreSQL second. Every portal reads from the local cache, so the interface remains responsive and usable when the network does not reach; a synchronisation service pushes each local change upward and applies each remote change downward. When connectivity is absent, changes accumulate in a queue and are replayed on reconnection, satisfying NFR1 and NFR6.' },
  { t: 'fig', n: '5.5', cap: 'System Architecture of the MamaTrack GPS System', img: 'fig01_system_architecture.png' },
  { t: 'p', x: 'The internal organisation of the codebase is shown in Figure 5.6, which groups the modules into portals, shared components and services, and shows which depend on the database and synchronisation layer. Each portal is compiled into its own bundle so that a mother on a limited data plan downloads her own interface and not the administrator’s, which is by a wide margin the largest.' },
  { t: 'fig', n: '5.6', cap: 'Module Architecture of the Application', img: 'fig02_module_architecture.png' },
  { t: 'p', x: 'The lifecycle of an emergency case is governed by the state machine in Figure 5.7. Constraining the case to defined states and transitions is what allows five portals to act on the same record without conflicting: a driver may move a case from dispatched to en-route but cannot complete it, and cancellation is permitted only before pickup.' },
  { t: 'fig', n: '5.7', cap: 'Emergency Case State Machine', img: 'fig08_state_machine.png' },
  { t: 'p', x: 'Figure 5.8 shows the ordered exchange that occurs during a dispatch, from the mother pressing the alert through position capture, facility resolution, driver assignment and clinical notification. This is the pathway validated end to end in Section 5.6.' },
  { t: 'fig', n: '5.8', cap: 'Sequence Diagram — Emergency Dispatch', img: 'fig09_sequence.png' },
  { t: 'p', x: 'Figure 5.9 shows the synchronisation mechanism that supports operation under intermittent connectivity: how local writes are queued when the network drops, how they are replayed on reconnection, and how remote rows are merged into the local cache without being echoed back to the server.' },
  { t: 'fig', n: '5.9', cap: 'Offline Synchronisation Mechanism', img: 'fig10_offline_sync.png' },

  { t: 'h3', n: '5.5.1', x: 'System Graphical User Interfaces' },
  { t: 'p', x: 'The interfaces below show the principal screens of the delivered system. The landing page presents the five portal entry points; the login screen authenticates a user into the portal matching their role; the mother’s console presents the emergency beacon and her live tracking map; the district command console presents the triage queue and fleet monitor; and the ambulance navigation panel presents the assigned case, route and patient brief.' },
  { t: 'shot', n: '5.10', cap: 'System Landing Page' },
  { t: 'shot', n: '5.11', cap: 'Portal Login Screen' },
  { t: 'shot', n: '5.12', cap: 'Expectant Mother Portal — Emergency Beacon and Live Tracking' },
  { t: 'shot', n: '5.13', cap: 'District Command Console — Triage Queue and Fleet Monitor' },
  { t: 'shot', n: '5.14', cap: 'Ambulance Navigation Panel' },

  { t: 'h3', n: '5.5.2', x: 'Sample Code' },
  { t: 'p', x: 'The extract below is the core of the emergency capture path. It illustrates the offline-first stance of the system: the case is written locally and broadcast immediately, and replication to PostgreSQL is a consequence of that write rather than a precondition for it, so an alert can be raised whether or not the network is reachable. Further extracts are given in Appendix VI.' },
  {
    t: 'code', x: [
      '// Raise an emergency for a mother and resolve her destination and responder.',
      'triggerEmergency(motherUserId: number, latitude: number, longitude: number) {',
      '  const mother   = db.mothers.find(m => m.user_id === motherUserId);',
      '  const hospital = this.findNearestCapableHospital(latitude, longitude);',
      '  const vehicle  = this.findAvailableVehicle(hospital.id);',
      '',
      '  const emergency: Emergency = {',
      '    id:          nextId(db.emergencies),',
      '    code:        `EMG-${new Date().getFullYear()}-${sequence()}`,',
      '    mother_id:   motherUserId,',
      '    latitude, longitude,',
      '    status:      \'pending\',',
      '    severity:    this.assessSeverity(mother),',
      '    hospital_id: hospital.id,',
      '    vehicle_id:  vehicle ? vehicle.id : null,',
      '    driver_id:   vehicle ? this.driverFor(vehicle.id) : null,',
      '    doctor_id:   this.onDutyObstetrician(hospital.id),',
      '    eta_minutes: this.estimateEta(vehicle, latitude, longitude),',
      '    created_at:  new Date().toISOString(),',
      '  };',
      '',
      '  // Written locally first; SyncService replicates upward and queues if offline.',
      '  db.emergencies = [...db.emergencies, emergency];',
      '',
      '  this.notifyResponders(emergency);',
      '  SmsService.sendSms(mother.next_of_kin_name, mother.next_of_kin_phone,',
      '    `MamaTrack ALERT: ${mother.name} has triggered an emergency beacon.`);',
      '',
      '  return emergency;',
      '}',
    ],
  },

  { t: 'h2', n: '5.6', x: 'System Testing and Validation' },
  { t: 'h3', n: '5.6.1', x: 'System Testing' },
  { t: 'p', x: 'Testing proceeded at the four levels described in Section 3.9.2. Static verification of the delivered source returned no compiler errors across all 25 modules and no warnings from static analysis. The production build completed successfully, emitting eleven bundles with an entry bundle of 388 kB, 97 kB when compressed. All five portals were then loaded and exercised in a browser: each rendered with live data and a working map, all 120 asset requests succeeded, and no uncaught errors were produced.' },
  { t: 'p', x: 'Testing identified five defects, all of which were corrected and re-verified. The most serious concerned the realtime subscription: when the synchronisation service initialised against a cached channel that had already been subscribed, registering change handlers raised an error that was not caught and terminated the entire interface. Because the alert function is the reason the system exists, the correction both removed the fault and ensured that any future failure of the realtime channel degrades the system to queued synchronisation rather than interrupting service. Two further defects concerned the loss of data captured offline — an unguarded parse of the synchronisation queue that would strand every pending change, and an unguarded parse of the offline emergency cache that could discard a queued alert. A fourth concerned diagnostic messages that reported success on failure paths, and a fifth comprised 52 static analysis warnings, since resolved.' },
  {
    t: 'tbl', n: '5.3', cap: 'Summary of System Test Results',
    head: ['Test', 'Method', 'Expected result', 'Outcome'],
    widths: [2300, 2400, 2400, 2260],
    rows: [
      ['Type correctness', 'TypeScript compiler over all modules', 'No errors', 'Passed — 0 errors'],
      ['Code quality', 'Static analysis over all modules', 'No warnings', 'Passed — 0 warnings'],
      ['Production build', 'Bundler build to distributable output', 'Build completes', 'Passed — 11 bundles'],
      ['Asset delivery', 'Network trace of a full page load', 'No failed requests', 'Passed — 120 of 120'],
      ['Portal rendering', 'Load each of the five portals', 'Renders with live data', 'Passed — all five'],
      ['Alert capture', 'Raise an alert from the mother portal', 'Case created with coordinates', 'Passed'],
      ['Facility resolution', 'Observe destination assigned', 'Nearest capable facility chosen', 'Passed'],
      ['Responder assignment', 'Observe vehicle and driver assigned', 'Available ambulance assigned', 'Passed'],
      ['Cross-device visibility', 'Observe case from a separate session', 'Case visible without shared state', 'Passed'],
      ['State progression', 'Follow the case through its lifecycle', 'States advance in defined order', 'Passed'],
    ],
  },

  { t: 'h3', n: '5.6.2', x: 'System Validation' },
  { t: 'p', x: 'Validation addressed the question of whether the system solves the problem stated in Chapter One. A simulated emergency scenario was executed: an alert was raised from the expectant mother portal, and the district command console was then opened in a physically separate browser session holding no local data from the first, and signed in as an administrator.' },
  { t: 'p', x: 'The case was already present. It appeared as reference EMG-2026-0031 for patient Nakato Fatima, with Mukono General Hospital resolved as the destination facility, driver Moses Kiggundu assigned in ambulance UBG 001A, the case advanced automatically through its dispatch states, and the alert plotted on the district map alongside eight facilities and five ambulances. Because the second session began with no shared local state, the case can only have reached it through the replication layer.' },
  { t: 'p', x: 'This single scenario validates the chain the study set out to build. The mother’s position was captured from her device rather than described; the destination was resolved from facility capability rather than by telephoning each in turn; the responder was assigned automatically; and the case became visible to an actor on another device within seconds. Measured against the second delay identified in Chapter One, the search phase that respondents reported as taking up to an hour is replaced by a coordinate available before the ambulance departs.' },

  { t: 'h2', n: '5.7', x: 'Chapter Summary' },
  { t: 'p', x: 'This chapter presented the design of the system through context, level 0 and level 1 Data Flow Diagrams and an Entity-Relationship Diagram; described the eleven-table database design and the data description of the central emergencies table; set out the implementation as an offline-first Progressive Web Application with its architecture, module organisation, state machine and dispatch sequence; and reported the testing and validation carried out. Testing returned a clean compilation, a clean static analysis and a successful build, and identified five defects that were corrected. Validation confirmed that an emergency raised on one device becomes visible, with position and assigned responder, on a separate device — the outcome the study set out to achieve.' },
];

const CH6 = [
  { t: 'h2', n: '6.1', x: 'Introduction' },
  { t: 'p', x: 'This chapter discusses the findings of the study in relation to its objectives, presents the recommendations arising from the work, states the limitations encountered, identifies areas for further research, and concludes.' },

  { t: 'h2', n: '6.2', x: 'Discussion' },
  { t: 'p', x: 'The first objective was to study and analyse the current maternal emergency response and referral workflow. The analysis in Chapter Four established a finding that shaped everything that followed: the weaknesses of the current pathway are informational while its strengths are social. Village Health Teams hold community trust, operators improvise skilfully, and paper cards work without power. None of these is something software supplies, and a system that displaced them would have removed the working parts of the pathway along with the broken ones. The decision to augment rather than replace follows directly from the analysis rather than from preference.' },
  { t: 'p', x: 'The second objective was to determine and specify the requirements for a system suited to the terrain of Mukono District. The terrain requirement proved to be a connectivity requirement. Because the areas with the longest transit times are also those with the weakest coverage, a system that required the network in order to raise an alert would have failed precisely where it was most needed. This produced NFR1 and the offline-first architecture described in Section 5.5, in which the local write is the alert and replication is a consequence of it.' },
  { t: 'p', x: 'The third objective was to design a system comprising a mobile interface for mothers and a centralised dashboard for administrators. The delivered system exceeds this, providing five portals rather than two, because the analysis showed that the information loss occurs at handovers, and the handovers involve Village Health Teams, drivers and clinicians as well as mothers and administrators. Placing the driver and the receiving clinician inside the same record removes two of the points at which location and clinical history previously degraded.' },
  { t: 'p', x: 'The fourth objective was to implement, test and validate the system through simulated emergency scenarios. The validation reported in Section 5.6.2 confirms the central claim: a case raised on one device reached a separate device carrying an accurate position, a resolved destination and an assigned responder. The finding most worth recording, however, emerged from testing rather than from validation. The most serious defect was not a compilation failure — compilation was already clean — but a realtime subscription fault capable of terminating the entire interface during startup. It was invisible to static analysis and appeared only when the running system was exercised. This supports a methodological point relevant beyond this project: for systems whose value lies in behaviour under adverse conditions, a green build is not evidence of correctness.' },
  { t: 'p', x: 'These findings are consistent with the literature reviewed in Chapter Two. The observation that geospatial coordination rather than communication is the binding constraint accords with the pilot evidence from Tanzania, Nigeria and Kenya. The study extends that evidence in one respect: where those pilots demonstrated that GPS integration reduces response times, this work shows that the integration must be designed to survive the absence of the network, or it will be unavailable in the settings that motivate it.' },

  { t: 'h2', n: '6.3', x: 'Recommendations' },
  { t: 'n', x: 'The district should adopt the system in a supervised pilot covering Mukono General Hospital and its immediately surrounding health centres before wider rollout, so that the dispatch workflow can be observed under real load before the island communities, which are the hardest case, are brought in.' },
  { t: 'n', x: 'The permissive database access policy used during development should be replaced with role-scoped policies bound to authenticated identity before any real patient record is entered. In its current demonstration configuration every table is readable and writable by any client, which is acceptable for seeded fictional data and unacceptable for clinical data.' },
  { t: 'n', x: 'User accounts should be migrated into the managed identity provider so that credentials are verified centrally rather than compared on the device, and so that password recovery and account revocation become possible.' },
  { t: 'n', x: 'Village Health Teams should be equipped with devices and trained as the field entry point for mother registration and vitals capture. Their coverage determines how much of the district the system can see, and a mother who is not registered cannot be located.' },
  { t: 'n', x: 'An error boundary should be added around the routed portals so that an unexpected failure in one view degrades to a recoverable message rather than a blank screen, which matters more in a field emergency than in an office setting.' },
  { t: 'n', x: 'The Ministry of Health and the district health office should use the accumulated emergency records to identify where response times concentrate, and should site additional ambulances and clinics accordingly. This capability is a by-product of the system and requires no additional development.' },

  { t: 'h2', n: '6.4', x: 'Limitations of the Study' },
  { t: 'b', x: 'Validation was carried out through simulated emergency scenarios rather than live obstetric emergencies. Simulation can establish that the information pathway works; it cannot establish how the system behaves when used by a frightened woman in labour, and no claim about clinical outcomes is made on the basis of it.' },
  { t: 'b', x: 'The system was tested over the connectivity available during the study period and not across the full range of conditions in the district, particularly on Lake Victoria, where coverage is most intermittent.' },
  { t: 'b', x: 'Position accuracy depends on the device geolocation provider and degrades where satellite visibility is poor. The system reports its accuracy but cannot improve on the receiver in the handset.' },
  { t: 'b', x: 'The study period of ten weeks permitted development and validation but not longitudinal measurement of response times before and after deployment, which is the measure that would ultimately settle the system’s effectiveness.' },
  { t: 'b', x: 'SMS notification to next of kin was implemented against a simulated gateway rather than a live aggregator, since no commercial gateway agreement was available within the study period.' },

  { t: 'h2', n: '6.5', x: 'Areas for Further Research' },
  { t: 'b', x: 'A longitudinal study measuring response times in Mukono District before and after deployment would establish the effect on the second delay empirically rather than by inference from the mechanism.' },
  { t: 'b', x: 'The synchronisation of spatial data over USSD and SMS bearers, for use where data connectivity is absent entirely, remains open and would extend the system’s reach into the island communities.' },
  { t: 'b', x: 'The integration of wearable physiological sensors to raise an alert automatically on detection of deterioration, rather than depending on the mother to act, would address cases in which she is unable to.' },
  { t: 'b', x: 'Predictive analysis over accumulated emergency and vitals records could support the identification of high-risk pregnancies before a crisis rather than during one.' },
  { t: 'b', x: 'The adaptation of the same architecture to other time-critical emergencies, such as road traffic injury or epidemic case reporting, would test the generality of the offline-first, location-aware pattern developed here.' },

  { t: 'h2', n: '6.6', x: 'Conclusion' },
  { t: 'p', x: 'This study set out to eliminate spatial invisibility in maternal emergency response in Mukono District by making a mother’s position visible to responders before she arrives at a facility. It analysed the existing referral pathway, specified the requirements of a system to augment it, designed that system using Data Flow, Entity-Relationship and UML models, implemented it as an offline-first Progressive Web Application serving five role-specific portals over a shared replicated database, and validated it through simulated emergency scenarios.' },
  { t: 'p', x: 'The system works. An alert raised on a mother’s device reaches a district command console on a separate device carrying an accurate position, a destination facility resolved from real capability, and an assigned ambulance and driver, and the receiving clinician is briefed before the patient arrives. The search phase that respondents described as consuming up to an hour is replaced by a coordinate available before the vehicle departs. Measured against the second delay identified in Chapter One, that is the substantive result of the work.' },
  { t: 'p', x: 'What remains is not primarily technical. The system’s access control is configured for demonstration and must be tightened before it holds a real patient record, and its coverage depends on Village Health Teams registering the mothers in their areas. Neither is a research problem. The research question — whether a location-aware emergency system can be built that remains usable in the conditions that make it necessary — has been answered in the affirmative, and the answer is that it can, provided the design treats the absence of the network as the normal case rather than the exception.' },
];

const REFERENCES = [
  'Faujdar, D.S. & Kumar, R. (2020). Geospatial Technology for Maternal Health Services: A Review of Applications in Low and Middle Income Countries. Journal of Family Medicine and Primary Care, 9(6), 2637–2643.',
  'Gabrysch, S. & Campbell, O.M.R. (2009). Still Too Far to Walk: Literature Review of the Determinants of Delivery Service Use. BMC Pregnancy and Childbirth, 9(34), 1–18.',
  'Lee, A.C., Lawn, J.E., Cousens, S. & Darmstadt, G.L. (2009). Linking Families and Facilities for Care at Birth: What Works to Avert Intrapartum-Related Deaths? International Journal of Gynecology and Obstetrics, 107, 65–88.',
  'Ministry of Health Uganda. (2021). Annual Health Sector Performance Report 2020/21. Kampala: Ministry of Health.',
  'National Planning Authority. (2020). Third National Development Plan (NDP III) 2020/21 – 2024/25. Kampala: National Planning Authority.',
  'Nyamtema, A.S., Urassa, D.P. & van Roosmalen, J. (2011). Maternal Health Interventions in Resource Limited Countries: A Systematic Review of Packages, Impacts and Factors for Change. BMC Pregnancy and Childbirth, 11(30), 1–12.',
  'Schmitz, M.M., Serbanescu, F., Kamara, V. & Kraft, J.M. (2019). Did Saving Mothers, Giving Life Expand Timely Access to Lifesaving Care in Uganda? Global Health: Science and Practice, 7(1), 146–160.',
  'Thaddeus, S. & Maine, D. (1994). Too Far to Walk: Maternal Mortality in Context. Social Science and Medicine, 38(8), 1091–1110.',
  'Uganda Bureau of Statistics. (2022). Uganda Demographic and Health Survey 2022. Kampala: Uganda Bureau of Statistics.',
  'UNICEF. (2019). mTrac: Strengthening Health Systems Through Mobile Technology in Uganda. Kampala: United Nations Children’s Fund.',
  'World Health Organization. (2016). WHO Recommendations on Antenatal Care for a Positive Pregnancy Experience. Geneva: World Health Organization.',
  'World Health Organization. (2023). Trends in Maternal Mortality 2000 to 2020. Geneva: World Health Organization.',
];

module.exports = { CH3, CH4, CH5, CH6, REFERENCES };
